# showdoc install
# need create /data/showdoc


version: '3'
services:
  showdoc:
    image: star7th/showdoc
    container_name: showdoc
    hostname: showdoc
    restart: unless-stopped
    ports:
      - 4999:80
    volumes:
      - /data/showdoc:/var/www/html
    privileged: true
    user: root
